name: tencent_trtccalling_plugin
description: A flutter package for tencent cloud TRTCSDK
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  tencent_im_plugin: ^0.2.44
  tencent_rtc_plugin: ^0.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
